# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Water Reminder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Water Reminder
  pod 'Charts'


  target 'Water ReminderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Water ReminderUITests' do
    # Pods for testing
  end

end
